# set version 3
version: "3"

services:
  # nsaid:
  #   build: .
  #   # run on network host
  #   network_mode: "host"
  #   # open all ros2 ports

  #   # put in interactive mode
  #   #tty: true
  #   # allow typing in
  #   #stdin_open: true
  #   # set security options
  #   security_opt:
  #     - seccomp:unconfined
  #   # set privileges
  #   privileged: true
  #   volumes:
  #     - .:/app
  #   # set environment variable
  #   environment:
  #     - ROS_DOMAIN_ID=11
  #     - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
  #     - RMW_FASTRTPS_USE_QOS_FROM_XML=1
  #     - FASTRTPS_DEFAULT_PROFILES_FILE=/app/fastdds.xml
  #   # run python script
  #   command: >
  #     bash -c "source /opt/ros/jazzy/setup.bash &&
  #     ros2 daemon stop &&
  #     ros2 daemon start &&
  #     source /opt/ros/jazzy/setup.bash &&
  #     watchmedo auto-restart --patterns='*.py' --recursive --
  #     python3 nsaid_est.py"

  # rover_iface:
  #   build: .
  #   # run on network host
  #   network_mode: "host"
  #   # open all ros2 ports

  #   # put in interactive mode
  #   #tty: true
  #   # allow typing in
  #   #stdin_open: true
  #   # set security options
  #   security_opt:
  #     - seccomp:unconfined
  #   # set privileges
  #   privileged: true
  #   volumes:
  #     - .:/app
  #   # set environment variable
  #   environment:
  #     - ROS_DOMAIN_ID=11
  #     - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
  #     - RMW_FASTRTPS_USE_QOS_FROM_XML=1
  #     - FASTRTPS_DEFAULT_PROFILES_FILE=/app/fastdds.xml
  #   # run python script
  #   command: >
  #     bash -c "ros2 daemon stop &&
  #     ros2 daemon start &&
  #     watchmedo auto-restart --patterns='*.py' --recursive --
  #     python3 rover_interface.py"

  bagger:
    build: .
    # run on network host
    network_mode: host
    pid: host
    ipc: host

    environment:
      - ROS_DOMAIN_ID=11
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    # put in interactive mode
    tty: true
    # allow typing in
    stdin_open: true
    # set security options
    security_opt:
      - seccomp:unconfined
    # set privileges
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - .:/app

    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
      cd /app &&
      ./rosbag_command.sh"
