# set version 3
version: "3"

services:
  interface:
    build: .
    # run on network host
    network_mode: host
    pid: host
    ipc: host

    environment:
      - ROS_DOMAIN_ID=11
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    # set security options
    security_opt:
      - seccomp:unconfined
    # set privileges
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - .:/app
    
    restart: unless-stopped

    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
      cd /app &&
      python3 rover_interface.py"
