function C0 = C_function(in1,in2,in3,in4,in5)
%C_function
%    C0 = C_function(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    30-May-2024 11:15:28

%{z_ddot_d, z_dot_d, z_dot, theta, k_vector}
c_af = in4(5,:);
c_d = in4(7,:);
c_rr = in4(4,:);
c_s = in4(6,:);
j_z = in4(2,:);
k = in4(3,:);
k1 = in5(1,:);
k2 = in5(2,:);
m = in4(1,:);
psi_dot = in3(2,:);
psi_dot_d = in2(2,:);
psi_ddot_d = in1(2,:);
x_dot = in3(1,:);
x_dot_d = in2(1,:);
x_ddot_d = in1(1,:);
y_dot = in3(3,:);
C0 = [-k1.*(x_dot-x_dot_d)+(c_rr.*x_dot+m.*x_ddot_d-m.*psi_dot.*y_dot)./k;-k2.*(psi_dot-psi_dot_d)+((((c_s.*psi_dot.*4.0+c_d.*y_dot.*2.5e+1).*(4.0./6.25e+2))./x_dot+j_z.*psi_ddot_d).*(2.5e+1./4.0))./c_af];
end
