function D = D_function(in1,in2,in3)
%D_function
%    D = D_function(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    30-May-2024 11:15:28

%{theta, z_dot, u}
c_af = in1(5,:);
c_d = in1(7,:);
c_rr = in1(4,:);
c_s = in1(6,:);
delta_in = in3(2,:);
i_in = in3(1,:);
j_z = in1(2,:);
k = in1(3,:);
m = in1(1,:);
psi_dot = in2(2,:);
x_dot = in2(1,:);
y_dot = in2(3,:);
t2 = 1.0./j_z;
t3 = 1.0./m;
t4 = 1.0./x_dot;
D = [psi_dot.*y_dot+i_in.*k.*t3-c_rr.*t3.*x_dot;c_af.*delta_in.*t2.*(4.0./2.5e+1)-c_s.*psi_dot.*t2.*t4.*(1.6e+1./6.25e+2)-c_d.*t2.*t4.*y_dot.*(4.0./2.5e+1);-psi_dot.*x_dot+c_af.*delta_in.*t3-c_d.*psi_dot.*t3.*t4.*(4.0./2.5e+1)-c_s.*t3.*t4.*y_dot];
end
