function W_n = W_n_function(in1,in2,in3)
%W_n_function
%    W_n = W_n_function(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    30-May-2024 11:15:28

%{z_ddot,  z_dot, u}
delta_in = in3(2,:);
i_in = in3(1,:);
psi_dot = in2(2,:);
psi_ddot = in1(2,:);
x_dot = in2(1,:);
x_ddot = in1(1,:);
y_dot = in2(3,:);
t2 = 1.0./x_dot;
W_n = reshape([x_ddot-psi_dot.*y_dot,0.0,0.0,psi_ddot,-i_in,0.0,x_dot,0.0,0.0,delta_in.*(-4.0./2.5e+1),0.0,psi_dot.*t2.*(1.6e+1./6.25e+2),0.0,t2.*y_dot.*(4.0./2.5e+1)],[2,7]);
end
