function W_z = W_z_function(in1,in2,in3)
%W_z_function
%    W_z = W_z_function(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    30-May-2024 11:15:28

%{z_ddot_d,  z_dot, theta_hat}
c_af_hat = in3(5,:);
c_d_hat = in3(7,:);
c_rr_hat = in3(4,:);
c_s_hat = in3(6,:);
j_z_hat = in3(2,:);
k_hat = in3(3,:);
m_hat = in3(1,:);
psi_dot = in2(2,:);
psi_ddot_d = in1(2,:);
x_dot = in2(1,:);
x_ddot_d = in1(1,:);
y_dot = in2(3,:);
t2 = psi_dot.*y_dot;
t3 = 1.0./k_hat;
t4 = 1.0./x_dot;
t5 = -t2;
t6 = t5+x_ddot_d;
W_z = reshape([t6,0.0,0.0,psi_ddot_d,-c_rr_hat.*t3.*x_dot+m_hat.*t3.*(t2-x_ddot_d),0.0,x_dot,0.0,0.0,(t4.*(c_s_hat.*psi_dot.*1.6e+1+c_d_hat.*y_dot.*1.0e+2+j_z_hat.*psi_ddot_d.*x_dot.*6.25e+2).*(-1.0./6.25e+2))./c_af_hat,0.0,psi_dot.*t4.*(1.6e+1./6.25e+2),0.0,t4.*y_dot.*(4.0./2.5e+1)],[2,7]);
end
