function z_ddot_d_function = z_ddot_d_function(t)
%Z_DDOT_D_FUNCTION
%    Z_DDOT_D_FUNCTION = Z_DDOT_D_FUNCTION(T)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    30-May-2024 11:15:28

%{t}
t2 = t.*(3.1e+1./1.0e+2);
t3 = cos(t2);
z_ddot_d_function = [t3.*(3.1e+1./1.0e+2),t3.*1.55e-2+cos(t.*(2.3e+1./1.0e+2)).*(2.3e+1./5.0e+2),0.0];
end
