function z_dot_d_function = z_dot_d_function(t)
%Z_DOT_D_FUNCTION
%    Z_DOT_D_FUNCTION = Z_DOT_D_FUNCTION(T)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    30-May-2024 11:15:28

%{t}
t2 = t.*(3.1e+1./1.0e+2);
t3 = sin(t2);
z_dot_d_function = [t3+2.0,t3./2.0e+1+sin(t.*(2.3e+1./1.0e+2))./5.0,0.0];
end
